version: '3'

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    restart: always
    ports:
      - 3000:3000
    networks:
      - hwei_network
  auth-service:
    container_name: auth-service
    build:
      context: .
      dockerfile: ./services/auth/Dockerfile
    restart: always
    ports:
      - 3001:3001
    networks:
      - hwei_network

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  hwei_network:
    driver: bridge
