#!/usr/bin/env sh
# Skip the build if running in a CI/CD environment
if [ "$CI" = "true" ]; then
  echo "Skipping build in CI/CD environment"
  exit 0
fi

echo "⚙️ Building monorepo..."
pnpm build
tput bel >/dev/tty 2>/dev/null || printf '\a'
